name: Release
on:
  release:
    types:
      - published
env:
  IMAGE: ${{ vars.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        PG_VERSION: [ "10", "11", "12", "13", "14", "15", "16" ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE }}:${{ matrix.PG_VERSION }}-${{ github.event.release.tag_name }}
          cache-from: type=registry,ref=${{ env.IMAGE }}:${{ matrix.PG_VERSION }}-buildcache
          cache-to: type=registry,ref=${{ env.IMAGE }}:${{ matrix.PG_VERSION }}-buildcache,mode=max
